services:
  - type: web
    name: pulseloop-ml
    runtime: python
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
