services:
  - type: web
    name: pulseloop-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: ML_SERVICE_URL
        value: https://pulseloop-ml.onrender.com
      - key: CORS_ORIGIN
        value: https://pulseloop.vercel.app
